spring:
  application:
    name: micro-service-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8764
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
